controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    gains:
      joint1:
        p: 1000.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
      joint2:
        p: 1000.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
